In [ ]:
from ultralytics import YOLO


In [ ]:
model_path = "datasets/YOLOv8_1/train_2/weights/best.pt"


In [1]:
from ultralytics import YOLO

model_path = "datasets/YOLOv8_1/train_2/weights/best.pt"

# Load a model
model = YOLO(model_path)  # pretrained YOLOv8n model

# Run batched inference on a list of images
results = model(source=[
    'datasets_sorted/PunggolMeridian_MRT/IMG_0008.JPG', 
    'datasets_sorted/PunggolMeridian_MRT/IMG_0019.JPG', 
    ],
    conf=0.8, iou=0.5, imgsz=800
    )  # return a list of Results objects


0: 608x800 2 interlocking-tiless, 1 road marking -good-, 1: 608x800 1 interlocking-tiles, 646.6ms
Speed: 8.2ms preprocess, 323.3ms inference, 10.7ms postprocess per image at shape (1, 3, 608, 800)


In [2]:
from PIL import Image
import numpy as np
import cv2

# Process results list
for result in results:
    print(result.names)
    cls = result.boxes.cls  # Boxes object for bbox outputs
    conf = result.boxes.conf  # Boxes object for bbox outputs
    print(cls, conf)

    sorted_cls, sorted_conf = [], []
    for label, confidence in zip(cls, conf):
        print(int(label), float(confidence))
        if confidence > 0.5:
            sorted_cls.append(label)
            sorted_conf.append(confidence)

    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs

    array = result.plot()
    array = array[:, :, ::-1]
    img = Image.fromarray(array)
    img.show()

    # print(array)


{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([1., 1., 5.]) tensor([0.9498, 0.9428, 0.8851])
1 0.9497528076171875
1 0.9427695870399475
5 0.885108232498169
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([1.]) tensor([0.9162])
1 0.9161919951438904


<a href="https://docs.ultralytics.com/modes/predict/#inference-arguments">Inference Arguments</a>

In [ ]:
from ultralytics import YOLO

model_path = "datasets/YOLOv8_1/train_2/weights/best.pt"

# Load a pretrained YOLOv8n model
model = YOLO(model_path)
# Everton, Punggol_blk160_166, Punggol_EdgeField_BLK105, Punggol_EdgeField_BLK111, PunggolMeridian_MRT, TiongBahru
image_path = "output/test/IMG_0019.JPG"
image_paths = [
    "datasets_sorted/PunggolMeridian_MRT/IMG_0008.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0021.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0025.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0035.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0041.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_9994.JPG",
    "datasets_sorted/TiongBahru/IMG_8823.JPG",
    "datasets_sorted/TiongBahru/IMG_8883.JPG",
    "datasets_sorted/TiongBahru/IMG_8884.JPG",
    "datasets_sorted/TiongBahru/IMG_8885.JPG",
    "datasets_sorted/TiongBahru/IMG_8895.JPG",
    "datasets_sorted/TiongBahru/IMG_8895.JPG",
    "datasets_sorted/TiongBahru/IMG_8926.JPG",
    "datasets_sorted/TiongBahru/IMG_8997.JPG",
    "datasets_sorted/TiongBahru/IMG_9012.JPG",
    "datasets_sorted/TiongBahru/IMG_9015.JPG",
]
video_path = "output/videos/GH012496_processed.mp4"

# Run inference on 'bus.jpg' with arguments
model.predict(video_path, save=True, imgsz=800, conf=0.5)

### Model Track

In [2]:
from ultralytics import YOLO

model_path = "datasets/YOLOv8_1/train_2/weights/best.pt"

# Load a pretrained YOLOv8n model
model = YOLO(model_path)
# Everton, Punggol_blk160_166, Punggol_EdgeField_BLK105, Punggol_EdgeField_BLK111, PunggolMeridian_MRT, TiongBahru
image_path = "output/test/IMG_0019.JPG"
image_paths = [
    "datasets_sorted/PunggolMeridian_MRT/IMG_0008.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0021.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0025.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0035.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0041.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_9994.JPG",
    "datasets_sorted/TiongBahru/IMG_8823.JPG",
    "datasets_sorted/TiongBahru/IMG_8883.JPG",
    "datasets_sorted/TiongBahru/IMG_8884.JPG",
    "datasets_sorted/TiongBahru/IMG_8885.JPG",
    "datasets_sorted/TiongBahru/IMG_8895.JPG",
    "datasets_sorted/TiongBahru/IMG_8895.JPG",
    "datasets_sorted/TiongBahru/IMG_8926.JPG",
    "datasets_sorted/TiongBahru/IMG_8997.JPG",
    "datasets_sorted/TiongBahru/IMG_9012.JPG",
    "datasets_sorted/TiongBahru/IMG_9015.JPG",
]
video_path = "output/videos/GH012496_processed.mp4"

# Run inference on 'bus.jpg' with arguments
results = model.track(source=video_path, conf=0.3, iou=0.5, show=True)



WARNING  inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (1/294) c:\D drive\2023 intern\Interlocking-Tiles-Defect-Detection\output\videos\GH012496_processed.mp4: 800x800 2 interlocking-tiless, 1 road marking -fade-, 1 road marking -good-, 675.4ms
video 1/1 (2/294) c:\D drive\2023 intern\Interlocking-Tiles-Defect-Detection\output\videos\GH012496_processed.mp4: 800x800 2 interlocking-tiless, 1 road marking -fade-, 1 road marking -good-, 622.0ms
video 1/1 (3/294) c:\D drive\2023 intern\Interlocking-Tile

In [3]:
from PIL import Image
import numpy as np
import cv2
from cv_functions import count_to_string

output_folder = "output/test_track"

count = 0
# Process results list
for result in results:
    print(result.names)
    boxes = result.boxes.cls  # Boxes object for bbox outputs
    boxes = result.boxes.conf  # Boxes object for bbox outputs
    print(boxes)
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs

    array = result.plot()
    array = array[:,:, ::-1]
    img = Image.fromarray(array)
    # img.show()

    img.save(f"{output_folder}/frame{count_to_string(count)}.jpg")

    count += 1


    # print(array)

{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.8756, 0.8598, 0.7915, 0.7204])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.8288, 0.8709, 0.8195, 0.8356])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.8215, 0.8666, 0.8117, 0.8322, 0.5228])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.8135, 0.8769, 0.7843, 0.8249, 0.6447])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.8233, 0.8473, 0.7671, 0.8568, 0.6183])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.7734,

### Create images to compare original photo and predicted photo

In [7]:
import cv2
import numpy as np
from cv_functions import get_image_dimensions, resize_save

img_name = 'IMG_9402.JPG'
original_image_path = 'test_images/IMG_9402.JPG'
predicted_image_path = 'test_images/predict/IMG_9402.JPG'

original_img = cv2.imread(original_image_path)
predicted_img = cv2.imread(predicted_image_path)

h, w = get_image_dimensions(original_image_path)
if w > h:
    og_img = cv2.resize(original_img, (800, 800))
    predict_img = cv2.resize(predicted_img, (800, 800))
else:
    og_img = cv2.resize(original_img, (800, 800))
    predict_img = cv2.resize(predicted_img, (800, 800))

# Stacking the original image with the predicted image
result = np.hstack((og_img, predict_img))
# cv2.imshow('Result', result)
# cv2.waitKey(0)

cv2.imwrite(f'output/predicts/new/{img_name}_predicted.jpg', result)

True