### Predicting

The following code performs predictions on `source` and returns `results`, which contains identified object data.
<br><br>
`model` : path to model.<br>
`source`: image path / list of image paths / and more. See <a href="https://docs.ultralytics.com/modes/predict/">documentation</a>.<br>
`conf`: confidence threshold.<br>
`iou`: IoU threshold. <br>
`imgsz`: size of image to infer with. current model was trained at 800.<br>

In [ ]:
from ultralytics import YOLO

model_path = "datasets/YOLOv8_1/train_2/weights/best.pt"

# Load a model
model = YOLO(model_path)  # pretrained YOLOv8n model

# Run batched inference on a list of images
results = model(
    source=
        # 'datasets_sorted/PunggolMeridian_MRT/IMG_0008.JPG', 
        # 'datasets_sorted/PunggolMeridian_MRT/IMG_0019.JPG', 
        'datasets_sorted/PunggolMeridian_MRT', 
    
    conf=0.8, iou=0.5, imgsz=800
    )  # return a list of Results objects

#### Shows and save predicted image

Change `save_path` to image path of choice.

In [ ]:
from PIL import Image
import numpy as np
import cv2

save_path = "output/test/hehe.jpg"

# Process results list
for result in results:
    print(result.names)
    cls = result.boxes.cls  # Boxes object for bbox outputs
    conf = result.boxes.conf  # Boxes object for bbox outputs
    print(cls, conf)

    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    # print(masks.data)
    # print(type(masks.data))
    # print(keypoints)
    # print(probs)

    array = result.plot()
    array = array[:, :, ::-1]
    img = Image.fromarray(array)
    # img.show()

    img.save(save_path)

### Predict image(s)/video

This directly saves predicted photo/video into a new folder. 

See <a href="https://docs.ultralytics.com/modes/predict/#inference-arguments">documentation</a> for more arguments.

<br> <br>
Change `image_path`, `image_paths`, or `video_path` and use either one of them in `source`.

In [4]:
from ultralytics import YOLO

model_path = "datasets/YOLOv8_1/train_2/weights/best.pt"

# Load a pretrained YOLOv8n model
model = YOLO(model_path)
# Everton, Punggol_blk160_166, Punggol_EdgeField_BLK105, Punggol_EdgeField_BLK111, PunggolMeridian_MRT, TiongBahru
image_path = "output/test/IMG_0019.JPG"
image_paths = [
    "datasets_sorted/PunggolMeridian_MRT/IMG_0008.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0021.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0025.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0035.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_0041.JPG",
    "datasets_sorted/PunggolMeridian_MRT/IMG_9994.JPG",
    "datasets_sorted/TiongBahru/IMG_8823.JPG",
    "datasets_sorted/TiongBahru/IMG_8883.JPG",
    "datasets_sorted/TiongBahru/IMG_8884.JPG",
    "datasets_sorted/TiongBahru/IMG_8885.JPG",
    "datasets_sorted/TiongBahru/IMG_8895.JPG",
    "datasets_sorted/TiongBahru/IMG_8895.JPG",
    "datasets_sorted/TiongBahru/IMG_8926.JPG",
    "datasets_sorted/TiongBahru/IMG_8997.JPG",
    "datasets_sorted/TiongBahru/IMG_9012.JPG",
    "datasets_sorted/TiongBahru/IMG_9015.JPG",
]
# folder_path
video_path = "output/videos/GH012496_processed.mp4"

# Run inference on with arguments, change source if needed
model.predict(source=video_path, save=True, imgsz=800, conf=0.5)



WARNING  inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (1/294) c:\D drive\2023 intern\Interlocking-Tiles-Defect-Detection\output\videos\GH012496_processed.mp4: 800x800 2 interlocking-tiless, 1 road marking -fade-, 2 road marking -good-s, 415.6ms
video 1/1 (2/294) c:\D drive\2023 intern\Interlocking-Tiles-Defect-Detection\output\videos\GH012496_processed.mp4: 800x800 2 interlocking-tiless, 1 road marking -fade-, 2 road marking -good-s, 415.6ms
video 1/1 (3/294) c:\D drive\2023 intern\Interlocking-Ti

[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: ultralytics.engine.results.Masks object
 names: {0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
 orig_img: array([[[160, 162, 155],
         [140, 142, 135],
         [174, 176, 169],
         ...,
         [163, 176, 170],
         [126, 139, 133],
         [168, 181, 175]],
 
        [[149, 151, 144],
         [128, 130, 123],
         [133, 135, 128],
         ...,
         [ 97, 110, 104],
         [ 51,  64,  58],
         [170, 183, 177]],
 
        [[131, 133, 126],
         [165, 167, 160],
         [159, 161, 154],
         ...,
         [104, 117, 111],
         [ 86,  99,  93],
         [184, 197, 191]],
 
        ...,
 
        [[ 42,  37,  36],
         [ 93,  88,  87],
         [120, 115, 114],
         ...,
         [100,  88,  90],
         [111,  99, 101],
   

### Model Track

Takes in a video at `video_path` and performs object tracking. Produces `results` for plotting later.

See <a href="https://docs.ultralytics.com/modes/track/">documentation</a>.

Change `model_path` to path to model. <br>
Change `video_path` to video of choice.

In [1]:
from ultralytics import YOLO

model_path = "datasets/YOLOv8_1/train_2/weights/best.pt"

# Load a pretrained YOLOv8n model
model = YOLO(model_path)

video_path = "C:/D drive/2023 intern/Interlocking Tiles Defect Detection GUI/test/vid-img-in/GH012496_trimmed.mp4"

# Run inference on 'bus.jpg' with arguments
results = model.track(source=video_path, conf=0.3, iou=0.5, show=False)



WARNING  inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (1/294) C:\D drive\2023 intern\Interlocking Tiles Defect Detection GUI\test\vid-img-in\GH012496_trimmed.mp4: 800x800 2 interlocking-tiless, 1 road marking -fade-, 510.6ms
video 1/1 (2/294) C:\D drive\2023 intern\Interlocking Tiles Defect Detection GUI\test\vid-img-in\GH012496_trimmed.mp4: 800x800 2 interlocking-tiless, 1 road marking -fade-, 443.1ms
video 1/1 (3/294) C:\D drive\2023 intern\Interlocking Tiles Defect Detection GUI\test\vid-img-in

#### Plot results onto each frame and saves it

Use 'Make Images into Video' in `processing.ipynb` afterwards to convert into video.

Change `output_folder` to where the frames should be stored.

In [2]:
from PIL import Image
import numpy as np

output_folder = "C:/D drive/2023 intern/Interlocking Tiles Defect Detection GUI/test/predict_track"

def count_to_string(count):
    l = 8
    return "0"*(l-len(str(count))) + str(count)

count = 0
# Process results list
for result in results:
    print(result.names)
    boxes = result.boxes.cls  # Boxes object for bbox outputs
    boxes = result.boxes.conf  # Boxes object for bbox outputs
    print(boxes)
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs

    array = result.plot()
    array = array[:,:, ::-1]
    img = Image.fromarray(array)
    # img.show()

    img.save(f"{output_folder}/frame{count_to_string(count)}.jpg")

    count += 1

{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.7896, 0.7372, 0.6373])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.7215, 0.6924, 0.6564])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.7352, 0.6949, 0.6600])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.7702, 0.6541, 0.7173])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.6430, 0.6510, 0.7285])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'manhole', 3: 'repair-tiles', 4: 'road marking -fade-', 5: 'road marking -good-'}
tensor([0.6707, 0.6230, 0.6949])
{0: 'asphalts', 1: 'interlocking-tiles', 2: 'm

### Create images to compare original photo and predicted photo

Produces image to compare original and predicted photos side-by-side.

Change `output_path`, `original_image_path`, or `predicted_image_path` to paths of choice.

In [ ]:
import cv2
import numpy as np

original_image_path = 'test_images/IMG_9402.JPG'
predicted_image_path = 'test_images/predict/IMG_9402.JPG'
output_path = 'output/predicts/new/IMG_9402.jpg'

original_img = cv2.imread(original_image_path)
predicted_img = cv2.imread(predicted_image_path)

image = cv2.imread(original_image_path)
h, w, channels = image.shape
if w > h:
    og_img = cv2.resize(original_img, (800, 800))
    predict_img = cv2.resize(predicted_img, (800, 800))
else:
    og_img = cv2.resize(original_img, (800, 800))
    predict_img = cv2.resize(predicted_img, (800, 800))

# Stacking the original image with the predicted image
result = np.hstack((og_img, predict_img))
# cv2.imshow('Result', result)
# cv2.waitKey(0)

cv2.imwrite(output_path, result)